# This file was generated by GoReleaser. DO NOT EDIT.
class GitDesc < Formula
  desc "Git descrption CLI Tool"
  homepage "https://github.com/miyazi777/gitdesc"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/miyazi777/git-desc/releases/download/v0.1.4/git-desc_0.1.4_darwin_amd64.tar.gz"
    sha256 "2360fea4b7878396be0edab6f5664a339233af6357469f5f469a4c7baf95cf3d"
  elsif OS.linux?
  end

  def install
    bin.install Dir['git-desc']
  end

  test do
    system "#{bin}/git-desc"
  end
end
