# This file was generated by GoReleaser. DO NOT EDIT.
class Gitdesc < Formula
  desc "Git descrption CLI Tool"
  homepage "https://github.com/miyazi777/gitdesc"
  version "0.1.1"

  if OS.mac?
    url "https://github.com/miyazi777/gitdesc/releases/download/v0.1.1/gitdesc_0.1.1_darwin_amd64.tar.gz"
    sha256 "0c8019b17f23ea0362fb54bf08ceb23106982684b5be32fd0157402b25fffb3a"
  elsif OS.linux?
  end

  def install
    bin.install Dir['gitdesc']
  end

  test do
    system "#{bin}/gitdesc"
  end
end
